config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, path: 'admin/users'

  
  resources :infos, path: 'admin/infos'
  resources :mainslides, path: 'admin/mainslides'
  resources :sections, path: 'admin/sections'
  resources :vendor_cats, path: 'admin/vendor_cats'
  resources :sidebars, path: 'admin/sidebars' 
  resources :galleries, path: 'admin/galleries'
  resources :contactus do
    collection do
      get 'thankspage'
    end
  end

  resources :albums, path: 'admin/albums'

  resources :posts, path: 'admin/posts'
  resources :categories, path: 'admin/categories'
  devise_for :vendors
  get 'undev/index'

  resources :articles, path: 'admin/articles'
  resources :admins, path: 'admin/admins'
  
  resources :vendors, path: 'admin/vendors'

  resources :homes do
    collection do
      get 'vendor'
      get 'vendorlist'
      get 'guest'
      get 'artikel'
      get 'wedding'
      get 'event'
      get 'coupon'
      get 'contact'
      get 'show_post'
      get 'vendor_search'
      get 'brides'
    end
  end

  get 'vendors/page'
  get 'vendors/member'
  get 'vendors/restrictarea'
  get 'vendors/pricelist'
  get 'vendors/frontview'

  match '/contacts', to: 'contacts#new', via: 'get'
  

  devise_for :admins
  
  get 'homes/index'
  get 'homes/about'

  get 'admins/noaccess'

  root 'undev#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image_url, ImageUploader       

  has_many :articles      
         
end

app/models/album.rb
class Album < ActiveRecord::Base

	validates :title, presence: true

	belongs_to 	:vendor

	has_many 	:gallery
	
end

app/models/article.rb
class Article < ActiveRecord::Base
	
	validates 	:category, :title, :body, :image_url, :admin_id, presence: true
	validates 	:image_url, allow_blank: false, format: {
	with: 		%r{\.(gif|jpg|png)\Z}i,
	message: 'must be a URL for GIF, JPG or PNG image.'
	}

	belongs_to 	:admin
	belongs_to 	:category
	has_many 	:vendor
	belongs_to 	:vendor

	#mount uploader untuk menjalankan class uploader
#formatnya adalah
# mount_uploader :field, Class
mount_uploader :image_url, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :title, presence: true

	has_many :articles
	validates_associated :articles

end

app/models/contactu.rb
class Contactu < ActiveRecord::Base

	validates :name, :email, :message, presence: true
	validates_format_of :email, :with => /@/

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	validates :album_id, :title, :image_url, presence: true

	belongs_to :album
	belongs_to :vendor

	mount_uploader :image_url, ImageUploader
end

app/models/home.rb
class Home < ActiveRecord::Base
	
end

app/models/info.rb
class Info < ActiveRecord::Base

	validates :image_url, :comp_name, :comp_address, :comp_phone, :comp_email, :comp_web, :comp_social, presence: true

	mount_uploader :image_url, ImageUploader
end

app/models/mainslide.rb
class Mainslide < ActiveRecord::Base

	validates :slidenumber, :cloud_url, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, :body, :section, :image_url, :kolom, presence: true

	belongs_to 	:vendor
	has_many 	:sections
	belongs_to	:section

	mount_uploader 	:image_url, ImageUploader	
end

app/models/section.rb
class Section < ActiveRecord::Base

	validates :name, presence: true

	has_many 	:vendors
	belongs_to 	:post
	has_many	:posts
	
end

app/models/sidebar.rb
class Sidebar < ActiveRecord::Base

	validates :title, :cloud_url, presence: true

	mount_uploader :image_url, ImageUploader
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  before_save :default_values
  def default_values
    self.section_id ||= 11
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validasi
  # validates	:name, :section, :description, :contactp, :email, :address, :city, presence: true      


	#mount uploader untuk menjalankan class uploader
	#formatnya adalah
	# mount_uploader :field, Class
	mount_uploader :image_url, ImageUploader

	has_many   	:posts, dependent: :destroy
	has_many   	:albums, dependent: :destroy
	has_many   	:galleries, dependent: :destroy
	belongs_to 	:article
	belongs_to  :section
	
	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	  where("city LIKE ?", "%#{search}%")
	end

	# def self.search(city, section_id)
	#   return scoped unless city.present? || section_id.present?
	# 	where(['city LIKE ? AND section_id = ?', "%#{city}%", section_id])
	# end

	# def self.search(title, company, location_id)
	#   return scoped unless title.present? || company.present? || location_id.present?
	#   where(['title LIKE ? AND company LIKE ? AND location_id = ?', "%#{title}%", "%#    
	#   {company}%", location_id])
	# end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/undev_helper.rb
module UndevHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
    
    <%= form_for(@admin) do |f| %>
      <% if @admin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

          <ul>
          <% @admin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  <div class="container">    
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <br>
      <!-- <div class="field">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
        </div>
        <br>
        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
        </div>
        <br> -->
        <div class="field">
          <%= f.label :upload_image, 'Upload Picture' %><br />
          <%= f.file_field :image_url %>
        </div>
        <br>
        <div class="field">
          <%= f.label :superadmin, 'SuperAdmin' %>
          <%= f.select(:superadmin, [
              ['Yes', 1], ['No', 0]
            ], class: 'form-control'
          )%>
        </div>
        <br>
      <div class="actions">
        <%= f.submit 'Save!', class: 'btn btn-default' %>
      </div>
    <% end %>
    <br>
  </div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="col-lg-9 col-md-9 col-sm-10">
    <h1>List Admin</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.name %></td>
            <td><%= admin.email %></td>
            <td><%= link_to '', admin, class: 'fa fa-eye' %></td>
            <td><%= link_to '', edit_admin_path(admin), class: 'fa fa-pencil-square-o' %></td>
            <td><%= link_to '', admin, class: 'fa fa-trash-o', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
</div>
<br>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/noaccess.html.erb
<div class="text-center">
	<h2>Sorry you are not allow to access this page</h2>
</div>

app/views/admins/show.html.erb
<div class="container">
<h1>Profile Admininstrator</h1>
<br>
	<form class="form-horizontal">
		<p id="notice"><%= notice %></p>

		<div class="form-group">
			<div class="col-sm-6">
				<%= image_tag(@admin.image_url, width: '50', height: '60', class: "img-circle") %>
			</div>	
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><strong>Name:</strong></label>
			<div class="col-sm-6">	
				<input type="text" class="form-control" placeholder="<%= @admin.name %>">
			</div>	
		</div>
		<div class="form-group">	
			<label class="col-sm-2 control-label"><strong>Email:</strong></label>
			<div class="col-sm-6">  
			  <input type="email" class="form-control" placeholder="<%= @admin.email %>">
			</div>  
		</div>
		<div class="form-group">	
			<label class="col-sm-2 control-label"><strong>SuperAdmin:</strong></label>
			<div class="col-sm-6">  
			  <input type="superadmin" class="form-control" placeholder="<%= @admin.superadmin %>">
			</div>  
		</div>
		


		<%= link_to 'Edit', edit_admin_path(@admin) %> |
		<%= link_to 'Back', admins_path %>

	</form>
</div>	

app/views/shared/_admin_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Administrator Page</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    
    

app/views/shared/_carousel.html.erb
<div class="row carousel-holder">
  <div class="col-md-12">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        
        <div class="item active">
        <% @mainslides1.each do |mainslide1| %>
          <%= image_tag(mainslide1.cloud_url, :alt => "slide1-from-cloud", class:"img-responsive") %>
          <div class="carousel-caption">
            <h3><%= mainslide1.title %></h3>
            <p><%= mainslide1.descrip %></p>
          </div>
        <% end %>
        </div>
        
        <div class="item">
        <% @mainslides2.each do |mainslide2| %>
          <%= image_tag(mainslide2.cloud_url, :alt => "slide2-form-cloud", class:"img-responsive") %>
          <div class="carousel-caption">
            <h3><%= mainslide2.title %></h3>
            <p><%= mainslide2.descrip %></p>
          </div>
        <% end %>  
        </div>

        <div class="item">
        <% @mainslides3.each do |mainslide3| %>
          <%= image_tag(mainslide3.cloud_url, :alt => "slide3-form-cloud", class:"img-responsive") %>
          <div class="carousel-caption">
            <h3><%= mainslide3.title %></h3>
            <p><%= mainslide3.descrip %></p>
          </div>
        <% end %>  
        </div>
      
      </div>

      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
  </div>  
</div>

app/views/shared/_footer.html.erb
<div class="container">	
	<div class="row bg-default">	
		<div class="col-xs-5 col-md-4">
	      <h3>Info</h3>
	      <ul class="list-unstyled">
			  <li><a href="#"><i class="fa fa-user fa-lg"></i></a> - About Us</li>
			  <li><a href="#"><i class="fa fa-phone fa-lg"></i></a> - Contact Us</li>
			  <li><a href="#"><i class="fa fa-ticket fa-lg"></i></a> - Pasang Coupon</li>
			  <li><a href="#"><i class="fa fa-pencil fa-lg"></i></a> - Pasang Iklan</li>
			</ul>
	  </div><!--/.col-xs-6.col-lg-4-->
	  <div class="col-xs-5 col-md-4">
	    <h3 class="">Social Media</h3>
	    <ul class="list-unstyled">
			  <li><a href="https://twitter.com/vendornikah"><i class="fa fa-twitter fa-lg"></i></a> - Twitter</li>
				<li><a href="https://www.facebook.com/vendornikah"><i class="fa fa-facebook fa-lg"></i></a> - Facebook</li>
				<li><a href="https://instagram.com/vendornikah"><i class="fa fa-instagram fa-lg"></i></a> - Instagram</li>
				<li><a href="https://www.youtube.com/channel/UCjgYV2FRWU-Xst2vlx5fdow"><i class="fa fa-youtube fa-lg"></i></a> - Youtube</li>
			</ul>
	  </div><!--/.col-xs-6.col-lg-4-->
	  <div class="col-xs-5 col-md-4">
	    <h3 class="">Other Projects</h3>
	    <ul class="list-unstyled">
			  <li><a href="http://www.mediaacara.com/"><i class="fa fa-chevron-right"></i> Media Acara</a></li>
			  <li><a href="http://www.promosibarangjasa.com"><i class="fa fa-chevron-right"></i> Promosi Barang & Jasa</a></li>
			  <li><a href="http://www.iklangratis-anda.com/"><i class="fa fa-chevron-right"></i> Iklan Gratis</li>
			  <li><a href="http://vendorpernikahan.com"><i class="fa fa-chevron-right"></i> Vendor Pernikahan</li>
			</ul>
	  </div><!--/.col-xs-6.col-lg-4-->
  </div>
</div>

	
	<div class="row bg-default" style="background-color:#B3B2B2; padding-top:6px">
		<p align="center">&copy; 2015 VendorPernikahan.Com</p>
	</div>

app/views/shared/_leftside.html.erb
<!-- lefside -->
<div class="leftside col-md-2 col-sm-3 col-xs-6">
	<p align="center" style="padding-top:10px">
	<%= image_tag(@article.admin.image_url, width: '35', height: '35', class: 'img-circle txt-center', :alt => 'admfoto') %> 
	</p>
	<hr>
	<ul class="list-unstyled list-inline">
		<li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
		<li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
		<li><a href="#"><i class="fa fa-instagram fa-lg"></i></a></li>
		<li><a href="#"><i class="fa fa-youtube fa-lg"></i></a></li>
	</ul>   
	<hr>        
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="navbar-brand" style="margin-top: -10px">
          <%= image_tag('logo_vp_word2.png', :alt => 'small-logo') %>
        </div>
        
    </div>
      <div id="navbar" class="collapse navbar-collapse">
        <% if vendor_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <div class="navbar-brand">
            <%= current_vendor.email %> |
            <%= link_to 'Logout', destroy_vendor_session_path, method: :delete %> |
            <%= link_to 'Vendor Area', vendors_page_path %>
          </div>  
            <% else %>
          <div class="navbar-brand navbar-right">  
            <%= link_to 'Login', new_vendor_session_path %> |
            <%= link_to 'Register', new_vendor_registration_path %>    
          </div>
        </ul>
        <% end %>
      </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

<%= render 'shared/row_header' %>

app/views/shared/_navbar_2nd.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Vendor', vendorlist_homes_path %></li>
        <li><%= link_to 'Artikel', artikel_homes_path %></li>
        <li><%= link_to 'Wedding Day', wedding_homes_path %></li>
        <li><%= link_to 'Event & Promo', event_homes_path %></li>
        <li><%= link_to 'Coupon', coupon_homes_path %></li>
        <li><%= link_to 'Contact Us', new_contactu_path %></li>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_navbar_top.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_row_header.html.erb
<div class="row-header img-responsive" style="background: #ccc url(http://s16.postimg.org/qr8up2679/Head_Banner_2_1200x122px.jpg);">
<!-- background-image: url("paper.gif"); -->
  <header>
    <!-- <div id="logo" align="center">
    	<%= image_tag("logo_vp_word1.png", :alt => "logvp") %>
    </div> -->
    
    <div id="logo" align="center" style="padding-top:15px">

		    <%= form_tag vendors_path, :method => 'get' do %>
				    <p>
				        <%= select_tag :section_id, options_from_collection_for_select(Section.all, :id, :name, params[:section_id]), include_blank: true, prompt: 'Vendor Category', class: '' %>
				        <%= text_field_tag :city, params[:city] %>

				        <%= submit_tag "Search", :name => nil %>
				    </p>
				<% end %>  
		    
    </div>

  	

  </header>
</div>

app/views/shared/_sidebar2.html.erb
<!-- <div class="list-group" style="padding-top:20px">
  <a href="#" class="list-group-item active">Last Article</a>
  <a href="#" class="list-group-item">Category 2</a>
  <a href="#" class="list-group-item">Category 3</a>
</div> -->

<ul class="list-group" style="padding-top:20px">
	<% @sidebars.each do |sidebar| %>	
  <li class="list-group-item text-center">
  	<%= link_to image_tag(sidebar.cloud_url), sidebar_path(sidebar) %><br>
  </li>
  <% end %>
</ul>

<!-- previous articles -->
<ul class="list-group" style="padding-top:20px">
  <li class="list-group-item active text-center lead">Previous Article</li>
  <% @articles2sb.each do |article2sb| %>
    <li class="list-group-item">
      <div class="media">
        <div class="media-left col-xs-4 col-md-4">
          <%= image_tag article2sb.image_url.url(:thumb), :alt => 'article2sb.title', class: 'img-responsive' %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to truncate(article2sb.title, length: 21), article_path(article2sb) %></h4>
          <p><%= truncate(strip_tags(article2sb.body), length: 40) %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<ul class="list-group" style="padding-top:20px">
  <li class="list-group-item active text-center lead">Previous Events</li>
  <% @articles3sb.each do |article3sb| %>
    <li class="list-group-item">
      <div class="media">
        <div class="media-left col-xs-4 col-md-4">
          <%= image_tag article3sb.image_url.url(:thumb), :alt => 'article3sb.title', class: 'img-responsive' %>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to truncate(article3sb.title, length: 21), article_path(article3sb) %></h4>
          <p><%= truncate(strip_tags(article3sb.body), length: 40) %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_slider.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("harmoni.jpg", :alt => "harmoni") %>
      <div class="carousel-caption">
        Slide Satu
      </div>
    </div>
    <div class="item">
      <%= image_tag("hati merah.png", :alt => "hati merah") %>
      <div class="carousel-caption">
        Slide Dua
      </div>
    </div>
    <div class="item">
      <%= image_tag("hearth_inside.jpg", :alt => "hearth_inside") %>
      <div class="carousel-caption">
        Slide Tiga
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_sliderowl.html.erb
<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px; height: 300px;">
    <!-- Slides Container -->
    <div u="slides" style="cursor: move; position: absolute; overflow: hidden; left: 0px; top: 0px; width: 600px; height: 300px;">
        <div><img u="image" src="image1.jpg" /></div>
        <div><img u="image" src="image2.jpg" /></div>
    </div>
</div>

<!-- it works the same with all jquery version from 1.x to 2.x -->
<script src="jquery.min.js"></script>
<script src="jssor.slider.mini.js"></script>
<script>
    jQuery(document).ready(function ($) {
        var options = { $AutoPlay: true };
        var jssor_slider1 = new $JssorSlider$('slider1_container', options);
    });
</script>