config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, path: 'admin/users'

  
  resources :infos, path: 'admin/infos'
  resources :mainslides, path: 'admin/mainslides'
  resources :sections, path: 'admin/sections'
  resources :vendor_cats, path: 'admin/vendor_cats'
  resources :sidebars, path: 'admin/sidebars' 
  resources :galleries, path: 'admin/galleries'
  resources :contactus do
    collection do
      get 'thankspage'
    end
  end

  resources :albums, path: 'admin/albums'

  resources :posts, path: 'admin/posts'
  resources :categories, path: 'admin/categories'
  devise_for :vendors
  get 'undev/index'

  resources :articles, path: 'admin/articles'
  resources :admins, path: 'admin/admins'
  
  resources :vendors, path: 'admin/vendors'

  resources :homes do
    collection do
      get 'vendor'
      get 'vendorlist'
      get 'guest'
      get 'artikel'
      get 'wedding'
      get 'event'
      get 'coupon'
      get 'contact'
      get 'show_post'
      get 'vendor_search'
      get 'brides'
    end
  end

  get 'vendors/page'
  get 'vendors/member'
  get 'vendors/restrictarea'
  get 'vendors/pricelist'
  get 'vendors/frontview'

  match '/contacts', to: 'contacts#new', via: 'get'
  

  devise_for :admins
  
  get 'homes/index'
  get 'homes/about'

  get 'admins/noaccess'

  root 'undev#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image_url, ImageUploader       

  has_many :articles      
         
end

app/models/album.rb
class Album < ActiveRecord::Base

	validates :title, presence: true

	belongs_to 	:vendor

	has_many 	:gallery
	
end

app/models/article.rb
class Article < ActiveRecord::Base
	
	validates 	:category, :title, :body, :image_url, :admin_id, presence: true
	validates 	:image_url, allow_blank: false, format: {
	with: 		%r{\.(gif|jpg|png)\Z}i,
	message: 'must be a URL for GIF, JPG or PNG image.'
	}

	belongs_to 	:admin
	belongs_to 	:category
	has_many 	:vendor
	belongs_to 	:vendor

	#mount uploader untuk menjalankan class uploader
#formatnya adalah
# mount_uploader :field, Class
mount_uploader :image_url, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :title, presence: true

	has_many :articles
	validates_associated :articles

end

app/models/contactu.rb
class Contactu < ActiveRecord::Base

	validates :name, :email, :message, presence: true
	validates_format_of :email, :with => /@/

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	validates :album_id, :title, :image_url, presence: true

	belongs_to :album
	belongs_to :vendor

	mount_uploader :image_url, ImageUploader
end

app/models/home.rb
class Home < ActiveRecord::Base
	
end

app/models/info.rb
class Info < ActiveRecord::Base

	validates :image_url, :comp_name, :comp_address, :comp_phone, :comp_email, :comp_web, :comp_social, presence: true

	mount_uploader :image_url, ImageUploader
end

app/models/mainslide.rb
class Mainslide < ActiveRecord::Base

	validates :slidenumber, :cloud_url, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, :body, :section, :image_url, :kolom, presence: true

	belongs_to 	:vendor
	has_many 	:sections
	belongs_to	:section

	mount_uploader 	:image_url, ImageUploader	
end

app/models/section.rb
class Section < ActiveRecord::Base

	validates :name, presence: true

	has_many 	:vendors
	belongs_to 	:post
	has_many	:posts
	
end

app/models/sidebar.rb
class Sidebar < ActiveRecord::Base

	validates :title, :cloud_url, presence: true

	mount_uploader :image_url, ImageUploader
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  before_save :default_values
  def default_values
    self.section_id ||= 11
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validasi
  # validates	:name, :section, :description, :contactp, :email, :address, :city, presence: true      


	#mount uploader untuk menjalankan class uploader
	#formatnya adalah
	# mount_uploader :field, Class
	mount_uploader :image_url, ImageUploader

	has_many   	:posts, dependent: :destroy
	has_many   	:albums, dependent: :destroy
	has_many   	:galleries, dependent: :destroy
	belongs_to 	:article
	belongs_to  :section
	
	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	  where("city LIKE ?", "%#{search}%")
	end

	# def self.search(city, section_id)
	#   return scoped unless city.present? || section_id.present?
	# 	where(['city LIKE ? AND section_id = ?', "%#{city}%", section_id])
	# end

	# def self.search(title, company, location_id)
	#   return scoped unless title.present? || company.present? || location_id.present?
	#   where(['title LIKE ? AND company LIKE ? AND location_id = ?', "%#{title}%", "%#    
	#   {company}%", location_id])
	# end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  layout 'admin'

  before_action :authenticate_admin!, except: [:show]

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all.order('created_at DESC') 
  end

  def show
    # sidebar
    @sidebars = Sidebar.where("active = 'Y'").order('created_at DESC').limit(6)
    # previous article in sidebar
    @articles2sb = Article.where("category_id = '2'").order('created_at DESC').limit('3,3')
    @articles3sb = Article.where("category_id = '3'").order('created_at DESC').limit('3,3')

    render layout: 'application'
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
    @category = Category.new
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :category, :category_id, :body, :image_url, :author, :harga_awal, :discount, :harga_sesudah, :time_awal, :time_akhir, :name, :vendor, :vendor_id, :description, :syarat, :info_vendor, :kolom, :admin_id)
    end

  # Membuat tanggal Indonesia

  def to_tanggal(mydate)
    # current_time = Time.now  
    # current_time.strftime("%B %d, %Y")  
    # => "March 13, 2014"

    
    
  end  

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/undev_helper.rb
module UndevHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
 <%= tinymce_assets %>

  <%= form_for(@article) do |f| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>


  <form>        
    <div class="form-group">  
      <%= f.label :Category, 'Article Category: ' %>
      <%= f.collection_select :category_id, Category.all, :id, :title, :prompt => 'Pilih Category', :multiple => true, :size => 5 %>  
    </div>
    
    <div class="form-group">    
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">  
        <%= f.label :body, 'Content' %><br>
        <%= f.text_area :body, :class => "tinymce", :rows => 20, :cols => 100 %>
        <%= tinymce %>
    </div>

    <div class="form-group">
      <%= f.label :upload_image, 'Upload Image *Usahakan Minimal Width: 255px dan Maksimal Width: 800px' %><br>
      <%= f.file_field :image_url %>
    </div>

    <div class="form-group">  
        <%= f.label :admin_id, 'Author' %><br>
        <%= f.collection_select :admin_id, Admin.all, :id, :name, :multiple => true, :prompt => 'Pilih Admin - Author', :size => 5 %>
    </div>

  <!-- khusus Coupons -->

  <a class="btn btn-primary btn-sm" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Khusus Category Coupon
  </a> <span class="text-danger">Klik it!</span>

  <div class="collapse" id="collapseExample">
    <div class="well">
      <div class="form-group">  
        <%= f.label :harga_awal %><br>
        <%= f.text_field :harga_awal, class: 'form-control' %>
      </div>
      <div class="form-group">  
        <%= f.label :Discount %><br>
        <%= f.text_field :discount, class: 'form-control' %>
      </div>

      <div class="form-group">  
          <%= f.label :Harga_sesudah %><br>
          <%= f.text_field :harga_sesudah, class: 'form-control' %>
      </div>
      <div class="form-group">  
        <%= f.label :Periode_awal %><br>
        <%= f.text_field :time_awal, 'data-provide' => 'datepicker' %>  
      </div>

      <div class="form-group">  
          <%= f.label :Periode_akhir %><br>
          <%= f.text_field :time_akhir, 'data-provide' => 'datepicker' %>
      </div>

      <div class="form-group">  
        <%= f.label :Nama_vendor %><br>
        <%= f.collection_select :vendor_id, Vendor.all, :id, :name, :multiple => true, :prompt => 'Pilih Vendor', :size => 5 %>
      </div>

      <div class="form-group">  
          <%= f.label :Syarat_ketentuan, "Syarat & Ketentuan" %><br>
          <%= f.text_area :syarat, class: 'form-control' %>
      </div>

      <div class="form-group">  
          <%= f.label :Info_vendor %><br>
          <%= f.text_area :info_vendor, class: 'form-control' %>        
      </div>

    </div>
  </div>
    
  <div class="form-group" style="padding-top:20px">  
      <%= f.submit 'Save', class: 'btn btn-primary btn-lg' %>
  </div> 

    <br> 
    <% end %>
  </form>

  <script type="text/javascript">
    $(document).ready(function(){
      $('.datepicker').datepicker();
    });
  </script>

app/views/articles/edit.html.erb
<div class="col-md-9 col-xs-12">	
	<h1>Editing Article</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
<br>
<br>
<br>
<br>
</div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row bg-primary">  
    <div class="col-md-7 col-xs-12"> 
      <h1>Listing Articles</h1>
    </div>
    <div class="col-md-5 col-xs-10 text-right" style="padding-top:20px"> 
      <%= link_to 'New Article', new_article_path, 'data-no-turbolink' => true, class: 'btn btn-default' %>
    </div>
  </div>  
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Category</th>
          <th>Body</th>
          <th>Image url</th>
          <th>Author</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.category.title if article.category %></td>
            <!-- <td><%= article.vendor.name if article.vendor %></td> -->
            <td><%= truncate(strip_tags(article.body), length: 100) %></td>
            <td><%= article.image_url %></td>
            <td><%= article.admin.name %></td>
            <td><%= link_to 'Show', article %></td>
            <td><%= link_to 'Edit', edit_article_path(article), 'data-no-turbolink' => true %></td>
            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
  <br>
  
</div>

app/views/articles/new.html.erb
<div class="col-md-9 col-xs-12">	
	
	<h1>New Article</h1>

	<%= render 'form' %>

	<%= link_to 'Back', articles_path %>
	<br>
	<br>
</div>

app/views/articles/show.html.erb
<div class="container"> 

  <div class="col-md-9 col-sm-9 col-xs-12">
    
    <p id="notice"><%= notice %></p>
  
      <p align="center">
        <%= image_tag(@article.image_url, :alt => @article.title, class: 'img-responsive') %>
      </p>
      
      <div class="caption">
        <h1><%= @article.title %></h1>  
        <p>
          <strong>Category:</strong>
          <%= @article.category.title %> |
          <strong>Author:</strong> 
          <%= @article.admin.name %> |
          <strong>Date: </strong>
          <%= @article.created_at.strftime("%d %B %Y") %> 
        </p>
        <hr>
        <br>  
        <!-- content -->
        <div class="row">

          <!-- leftside -->
          <%= render 'shared/leftside' %>
          <!-- #leftside -->
        
          <!-- main content -->
          <div class="content col-md-10 col-sm-10 col-xs-12">
            <p>
              <%= sanitize @article.body %>
            </p>

            <!--+++ condition if category +++-->
            <style type="text/css">
              p.bg{ background-color: #eee;

              }
            </style>

            <% if @article.category.title == 'Coupon' %>
              <p class="bg">
                <strong>Harga Awal:</strong>
                <%= @article.harga_awal %>
              </p>

              <p>
                <strong><i class="fa fa-tag" style="color:#E6A33F"></i> Discount: </strong>
                <%= @article.discount %>
              </p>

              <p class="bg">
                <strong>Harga Sesudah:</strong>
                <%= @article.harga_sesudah %>
              </p>

              <p>
                <strong>Periode Awal:</strong>
                <%= @article.time_awal %>
              </p>

              <p class="bg">
                <strong>Periode Akhir:</strong>
                <%= @article.time_akhir %>
              </p>

              <p>
                <strong>Nama Vendor:</strong>
                <%= @article.vendor.name if @article.vendor %>
              </p>

              <p class="bg">
                <strong>Syarat & Ketentuan:</strong>
                <%= @article.syarat %>
              </p>

              <p>
                <strong>Info Vendor:</strong>
                <%= @article.info_vendor %>
              </p>
            <% end %>
          </div><!-- content -->        
        </div><!-- row -->     
      </div>  
      
        
      <br>
      <br>

      <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_article_path(@article), 'data-no-turbolink' => true %> |
        <%= link_to 'Back', articles_path %>
      <% end %>  
      <br>
      <br>

      <!-- other story -->

      <!-- comments -->

    </div>

    <!-- sidebar -->
    <div class="col-md-3">
      <%= render 'shared/sidebar2' %>
    </div>

    <div class="row">
      
    </div>


</div>  