config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users, path: 'admin/users'

  
  resources :infos, path: 'admin/infos'
  resources :mainslides, path: 'admin/mainslides'
  resources :sections, path: 'admin/sections'
  resources :vendor_cats, path: 'admin/vendor_cats'
  resources :sidebars, path: 'admin/sidebars' 
  resources :galleries, path: 'admin/galleries'
  resources :contactus do
    collection do
      get 'thankspage'
    end
  end

  resources :albums, path: 'admin/albums'

  resources :posts, path: 'admin/posts'
  resources :categories, path: 'admin/categories'
  devise_for :vendors
  get 'undev/index'

  resources :articles, path: 'admin/articles'
  resources :admins, path: 'admin/admins'
  
  resources :vendors, path: 'admin/vendors'

  resources :homes do
    collection do
      get 'vendor'
      get 'vendorlist'
      get 'guest'
      get 'artikel'
      get 'wedding'
      get 'event'
      get 'coupon'
      get 'contact'
      get 'show_post'
      get 'vendor_search'
      get 'brides'
    end
  end

  get 'vendors/page'
  get 'vendors/member'
  get 'vendors/restrictarea'
  get 'vendors/pricelist'
  get 'vendors/frontview'

  match '/contacts', to: 'contacts#new', via: 'get'
  

  devise_for :admins
  
  get 'homes/index'
  get 'homes/about'

  get 'admins/noaccess'

  root 'undev#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image_url, ImageUploader       

  has_many :articles      
         
end

app/models/album.rb
class Album < ActiveRecord::Base

	validates :title, presence: true

	belongs_to 	:vendor

	has_many 	:gallery
	
end

app/models/article.rb
class Article < ActiveRecord::Base
	
	validates 	:category, :title, :body, :image_url, :admin_id, presence: true
	validates 	:image_url, allow_blank: false, format: {
	with: 		%r{\.(gif|jpg|png)\Z}i,
	message: 'must be a URL for GIF, JPG or PNG image.'
	}

	belongs_to 	:admin
	belongs_to 	:category
	has_many 	:vendor
	belongs_to 	:vendor

	#mount uploader untuk menjalankan class uploader
#formatnya adalah
# mount_uploader :field, Class
mount_uploader :image_url, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :title, presence: true

	has_many :articles
	validates_associated :articles

end

app/models/contactu.rb
class Contactu < ActiveRecord::Base

	validates :name, :email, :message, presence: true
	validates_format_of :email, :with => /@/

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	validates :album_id, :title, :image_url, presence: true

	belongs_to :album
	belongs_to :vendor

	mount_uploader :image_url, ImageUploader
end

app/models/home.rb
class Home < ActiveRecord::Base
	
end

app/models/info.rb
class Info < ActiveRecord::Base

	validates :image_url, :comp_name, :comp_address, :comp_phone, :comp_email, :comp_web, :comp_social, presence: true

	mount_uploader :image_url, ImageUploader
end

app/models/mainslide.rb
class Mainslide < ActiveRecord::Base

	validates :slidenumber, :cloud_url, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, :body, :section, :image_url, :kolom, presence: true

	belongs_to 	:vendor
	has_many 	:sections
	belongs_to	:section

	mount_uploader 	:image_url, ImageUploader	
end

app/models/section.rb
class Section < ActiveRecord::Base

	validates :name, presence: true

	has_many 	:vendors
	belongs_to 	:post
	has_many	:posts
	
end

app/models/sidebar.rb
class Sidebar < ActiveRecord::Base

	validates :title, :cloud_url, presence: true

	mount_uploader :image_url, ImageUploader
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  before_save :default_values
  def default_values
    self.section_id ||= 11
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validasi
  # validates	:name, :section, :description, :contactp, :email, :address, :city, presence: true      


	#mount uploader untuk menjalankan class uploader
	#formatnya adalah
	# mount_uploader :field, Class
	mount_uploader :image_url, ImageUploader

	has_many   	:posts, dependent: :destroy
	has_many   	:albums, dependent: :destroy
	has_many   	:galleries, dependent: :destroy
	belongs_to 	:article
	belongs_to  :section
	
	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	  where("city LIKE ?", "%#{search}%")
	end

	# def self.search(city, section_id)
	#   return scoped unless city.present? || section_id.present?
	# 	where(['city LIKE ? AND section_id = ?', "%#{city}%", section_id])
	# end

	# def self.search(title, company, location_id)
	#   return scoped unless title.present? || company.present? || location_id.present?
	#   where(['title LIKE ? AND company LIKE ? AND location_id = ?', "%#{title}%", "%#    
	#   {company}%", location_id])
	# end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  layout 'admin'

  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:comp_name, :comp_address, :comp_phone, :comp_email, :comp_web, :comp_social, :image_url)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/undev_helper.rb
module UndevHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url, 'Add Logo' %><br>
    <%= f.file_field :image_url %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_name, 'Company Name' %><br>
    <%= f.text_field :comp_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_address, 'Address' %><br>
    <%= f.text_area :comp_address, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_phone, 'Phone' %><br>
    <%= f.number_field :comp_phone, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_email, 'Email' %><br>
    <%= f.text_field :comp_email, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_web, 'Website' %><br>
    <%= f.text_field :comp_web, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :comp_social, 'Social Media' %><br>
    <%= f.text_area :comp_social, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
  <br>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>
<br><br><br>

app/views/infos/index.html.erb
<div class="container">
  <div class="col-md-10">
    <p id="notice"><%= notice %></p>

    <h1>Company Info</h1>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Comp name</th>
          <th>Comp address</th>
          <th>Comp phone</th>
          <th>Comp email</th>
          <th>Comp web</th>
          <th>Comp social</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @infos.each do |info| %>
          <tr>
            <td><%= info.comp_name %></td>
            <td><%= info.comp_address %></td>
            <td><%= info.comp_phone %></td>
            <td><%= info.comp_email %></td>
            <td><%= info.comp_web %></td>
            <td><%= info.comp_social %></td>
            <td><%= link_to '', info, class: 'fa fa-eye' %></td>
            <td><%= link_to '', edit_info_path(info), class: 'fa fa-pencil-square-o' %></td>
            <td><%= link_to '', info, class: 'fa fa-trash-o', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Info', new_info_path %>
  </div>  
</div>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>
<br>
<br>
<br>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <!-- Logo Company -->
  <%= image_tag(@info.image_url) %>
</p>
<p>
  <strong>Comp name:</strong>
  <%= @info.comp_name %>
</p>

<p>
  <strong>Comp address:</strong>
  <%= @info.comp_address %>
</p>

<p>
  <strong>Comp phone:</strong>
  <%= @info.comp_phone %>
</p>

<p>
  <strong>Comp email:</strong>
  <%= @info.comp_email %>
</p>

<p>
  <strong>Comp web:</strong>
  <%= @info.comp_web %>
</p>

<p>
  <strong>Comp social:</strong>
  <%= @info.comp_social %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>